services:
  xampp:
    image: tomsik68/xampp:7
    container_name: eduwork_xampp
    restart: unless-stopped
    volumes:
      - "./Sesi 7:/opt/lampp/htdocs"
      - "./Sesi 8:/opt/lampp/htdocs/Sesi8"
      - "./Sesi 9:/opt/lampp/htdocs/Sesi9"
      - mysql_data:/opt/lampp/var/mysql
    ports:
      - "8080:80"
      - "3307:3306"

volumes:
  mysql_data:
