USE `Sesi 9`;

INSERT INTO `products` (`name`, `description`, `image`, `price`, `stock`, `category`) VALUES
  ('Kursi Kantor Ergonomis', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 850000, 25, 'Furnitur'),
  ('Meja Belajar Minimalis', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 1250000, 10, 'Furnitur'),
  ('Sofa Bed 3 Seater', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 3450000, 6, 'Furnitur'),
  ('Rak Buku Kayu Jati', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 975000, 18, 'Furnitur'),
  ('Lemari Pakaian 2 Pintu', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 2650000, 4, 'Furnitur'),
  ('Lampu Meja LED', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 175000, 60, 'Elektronik'),
  ('Kipas Angin Portable USB', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 95000, 8, 'Elektronik'),
  ('Speaker Bluetooth Mini', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 299000, 35, 'Elektronik'),
  ('Headphone Wireless ANC', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 725000, 12, 'Elektronik'),
  ('Mouse Wireless Silent', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 130000, 0, 'Elektronik'),
  ('Keyboard Mechanical', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 475000, 22, 'Elektronik'),
  ('Powerbank 20000mAh', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 385000, 45, 'Elektronik'),
  ('Tas Ransel Anti Air', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 275000, 40, 'Aksesoris'),
  ('Dompet Kulit Premium', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 189000, 55, 'Aksesoris'),
  ('Tumbler Stainless 750ml', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 149000, 70, 'Aksesoris'),
  ('Topi Baseball Casual', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 85000, 33, 'Aksesoris'),
  ('Payung Lipat Otomatis', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 99000, 28, 'Aksesoris'),
  ('Botol Minum Tritan 1L', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 119000, 61, 'Aksesoris'),
  ('Buku Tulis A5 Isi 60', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 22000, 120, 'Alat Tulis'),
  ('Pulpen Gel 0.5mm (Pack)', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 45000, 90, 'Alat Tulis'),
  ('Stabilo Highlighter 6 Warna', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 68000, 48, 'Alat Tulis'),
  ('Map Dokumen Transparan', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 18000, 150, 'Alat Tulis'),
  ('Spidol Whiteboard Set', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 72000, 37, 'Alat Tulis'),
  ('Kalkulator 12 Digit', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 165000, 26, 'Alat Tulis'),
  ('Kemeja Flannel Pria', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 195000, 21, 'Fashion'),
  ('Kaos Polos Premium', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 89000, 75, 'Fashion'),
  ('Celana Chino Slim Fit', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 245000, 32, 'Fashion'),
  ('Jaket Hoodie Unisex', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 325000, 17, 'Fashion'),
  ('Sepatu Running Ringan', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 545000, 9, 'Fashion'),
  ('Sandal Jepit Nyaman', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 75000, 82, 'Fashion'),
  ('Handuk Microfiber Set', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 118000, 44, 'Perlengkapan Rumah'),
  ('Sprei Queen Bed 180', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 265000, 15, 'Perlengkapan Rumah'),
  ('Bantal Sofa Dacron', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 98000, 39, 'Perlengkapan Rumah'),
  ('Gorden Blackout 120x180', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 215000, 11, 'Perlengkapan Rumah'),
  ('Karpet Bulu Ruang Tamu', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 389000, 7, 'Perlengkapan Rumah'),
  ('Lampu Tidur Malam 3 Mode', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 134000, 29, 'Perlengkapan Rumah'),
  ('Piring Keramik Dinner Set', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 249000, 24, 'Perlengkapan Rumah'),
  ('Gelas Kaca Premium 6pcs', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 129000, 52, 'Perlengkapan Rumah'),
  ('Panci Set Anti Lengket', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 595000, 13, 'Perlengkapan Rumah'),
  ('Wajan Teflon 28cm', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 175000, 31, 'Perlengkapan Rumah'),
  ('Rice Cooker 1.8L', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 349000, 27, 'Elektronik'),
  ('Blender Portable 350ml', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 225000, 19, 'Elektronik'),
  ('Kulkas Mini 100L', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 2750000, 3, 'Elektronik'),
  ('Monitor 24 Inch IPS', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 1990000, 8, 'Elektronik'),
  ('Printer Inkjet WiFi', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 1245000, 5, 'Elektronik'),
  ('Webcam HD 1080p', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 285000, 16, 'Elektronik'),
  ('Router WiFi Dual Band', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 425000, 14, 'Elektronik'),
  ('Charger 65W GaN', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 265000, 38, 'Elektronik'),
  ('Kabel USB-C 2 Meter', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 45000, 88, 'Elektronik'),
  ('Casing Keyboard Silikon', 'Produk berkualitas dengan harga bersahabat, siap kirim ke seluruh Indonesia.', 'Asics.avif', 78000, 0, 'Elektronik');
